### ISSUE TITLE
9 - Enhanced eCommerce Search Block (e.g. Discount for all x / “red” products, see Quanta block)

### ISSUE THREAD

**Issue by TomEpiServer** [episerver/Commerce-Demo-Kit#5]

**Comment by evest** [comment]
There is already such a block:
![epic-photo-configurable-search-block-preview](https://cloud.githubusercontent.com/assets/6423464/10694888/fb6a43aa-79a0-11e5-8910-51c94eef0e49.png)

All props:
![epic-photo-configurable-search-block-props](https://cloud.githubusercontent.com/assets/6423464/10695272/39d705e0-79a3-11e5-8424-e974fa10b92a.png)

Filter:
![epic-photo-configurable-search-block-discount-filter](https://cloud.githubusercontent.com/assets/6423464/10695284/43c75c6c-79a3-11e5-8274-009b9225e4ad.png)

Available fields for numeric filter:
![epic-photo-configurable-search-block-discount-filter-fields](https://cloud.githubusercontent.com/assets/6423464/10695310/60ba5e78-79a3-11e5-9067-a070a5d81015.png)

It is missing sorting though.

**Comment by TomEpiServer** [comment]
I have setup a scenario for performing a SALE scenario demo.
You just need to upload the attached image to Media on you EpicPhoto installation.
The video with the scenario is on https://vimeo.com/149125001 

![1200x300camerasale](https://cloud.githubusercontent.com/assets/12154142/11836866/add87cb2-a3dd-11e5-9e26-eedededda6ae.png)

**Comment by petriisola** [comment]
Thanks TomEpiServer! Nice video.
